### PR TITLE
Fixed a bug with critical error on "0" exitcode

### PR DESCRIPTION
**Pull request by xaionaro**
There was a critical error when exitcodes are set in config file:

Normal: Unknown exitcode "0" with Modify on [...]
Error: Critical exitcode.

Variable "rc" at the moment of "Normal: Unknown exitcode" was "(nil)"

### CODE REVIEW

**Comment by axkibe** [comment]
exitcode 0 must be defined to be 'ok' by exitcodes.

**Comment by xaionaro** [comment]
> exitcode 0 must be defined to be 'ok' by exitcodes.

At the moment of the bug it *was*.

**Comment by axkibe** [comment]
Yes I'm sorry I let this lie for so long. If you find the time, can you recheck with current HEAD in git, and if the bug still persits post the exact configuration that raises it?

I have the feeling this patch doesn't patch the real issue if it still exists.

**Comment by xaionaro** [comment]
Yes, seems the patch is only a workaround for real problem. But I had to stop using lsyncd due to some other our issues… So it's quite difficult to recheck the bug. Sorry :(

**Comment by xaionaro** [comment]
Also, may be there wasn't fault of lsyncd, but we spent about 40 hours for rechecking everything. It appeared to easier write an own utility to do what we need for our exotic use cases.

**Comment by axkibe** [comment]
I see. I also suppose you aren't mad if I leave this patch unapplied and closed?

Thank you for trying to help to improve Lsyncd tough.

Kind regards.

**Comment by xaionaro** [comment]
> I see. I also suppose you aren't mad if I leave this patch unapplied and closed?

Of course. :)

**Pull request closed without merging**
