### PR TITLE
Add rsync.inplace option

### PR DESCRIPTION
**Pull request by dajhorn**
Pass the --inplace flag to the rsync process like this:

	sync {
		default.rsync,
		rsync = {
			inplace = true
		}
	}

Closes: #197

### CODE REVIEW

**Comment by aidin3000** [comment]
Even after modifying the files as noted in the commit, I get this error:

Error: error preparing /etc/lsyncd/lsyncd.conf.lua: Parameter "rsync.inplace" unknown. (if this is not a typo add it to checkgauge)

**Comment by axkibe** [comment]
Adding to Lsyncd 5.1.6

**Comment by JaapJoris** [comment]
I don't think this option should be enabled by default. From the rsync man page:

> The file’s data will be in an inconsistent state during the transfer and will be left that way if the transfer is interrupted or if an update fails

A major use case for lsyncd is synchronizing one's home directory to a remote server while on the go. In this case, silently enabling --inplace will leave unsuspecting users with corrupted files when their network connection drops.

**Comment by dajhorn** [comment]
@JaapJoris, the `--inplace` behavior is not enabled by default.  Look at the new option in full context here:

* https://github.com/axkibe/lsyncd/blob/master/default-rsync.lua#L68

Things like `--dry-run` are, similarly, not enabled by default.

**Pull request closed without merging**
